name: Build

on:
  push:
    branches:
      - main
      - nightly-version-support # TODO: Remove after testing
  pull_request:

jobs:
  plugin_test:
    name: Test ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test latest
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: snforge --version && sncast --version

      - name: Test nightly
        uses: asdf-vm/actions/plugin-test@v3
        with:
          version: latest:nightly
          command: snforge --version | grep "nightly" && sncast --version | grep "nightly"
